name: flutter_video_app
description: a play anime app
version: 0.6.9

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 本地化
  flutter_localizations:
    sdk: flutter
  intl:
  intl_translation:

  cupertino_icons: ^0.1.2
  rxdart:
  built_value:
  built_collection:
  url_launcher:
  mobx:
  flutter_mobx:
  sensors:
  html:
  webview_flutter:

  moor:
  moor_ffi:
  path_provider:
  path:
    
  package_info:
  
  # 可滑动列表项
  flutter_slidable: ^0.5.4
  
  # 底部泡泡栏
  bubble_bottom_bar: ^1.2.0
  
  video_box: ^0.11.2
  flutter_ajanuw_router: ^0.3.5
  ajanuw_http: ^0.2.0
  # apk升级策略
  flutter_github_releases_service: ^0.4.2
  breakpoints: ^0.2.0
  
  get_it: ^4.0.1
  toast:

  flutter_screen:
    git:
      url: https://github.com/januwA/flutter_screen
      ref: master

  flutter_android_pip:
    git:
      url: https://github.com/januwA/flutter_android_pip
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  built_value_generator:
  mobx_codegen:
  moor_generator:

flutter:
  uses-material-design: true
  assets:
    - assets/images/drawer_header.jpg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
